- name: Install Docker prerequisites
  hosts: linux
  become: yes
  tasks:
    - name: Install yum-utils
      ansible.builtin.package:
        name: yum-utils
        state: present

- name: Add Docker repository
  hosts: linux
  become: yes
  tasks:
    - name: Add Docker's official repository
      ansible.builtin.command: 
        cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker packages
  hosts: linux
  become: yes
  tasks:
    - name: Install Docker CE packages
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

- name: Start Docker service
  hosts: linux
  become: yes
  tasks:
    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
