---
- name: Deploy Apache Docker container
  hosts: all
  become: true
  tasks:
    - name: Pull Apache httpd image
      docker_image:
        name: httpd
        state: present
        source: pull  # Set source to pull
