---
- name: Deploy Apache Docker container
  hosts: all  # Replace with specific hosts if needed
  become: true
  tasks:
    - name: Pull Apache image
      docker_image:
        name: httpd
        state: present

    - name: Run Apache container
      docker_container:
        name: my_apache_container  # Customize container name
        image: httpd
        state: started
        ports:
          - "80:80"  # Map container port 80 to host port 80
        volumes:
          - "/path/to/your/content:/usr/local/apache2/htdocs"  # Optional: Mount volume for content
