- name: Install Docker and deploy Apache container on Linux
  hosts: linux
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose
      tags:
        - docker

    - name: Changing Docker daemon configuration file network
      copy:
        content: |
          {
            "bip": "172.168.10.1/30"
          }
        dest: /etc/docker/daemon.json
      notify: restart docker

    - name: Start Docker service
      service:
        name: docker
        state: started
      tags:
        - docker

    - name: Deploy Apache Docker container
      docker_container:
        name: "apache"
        image: "httpd:latest"
        state: started
        ports:
          - 80:80
      tags:
        - docker
