# deploy_apache_container.yml

- name: Deploy Apache container using Docker
  hosts: localhost
  become: true
  tasks:
    - name: Install Docker dependencies
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Add Docker repository
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        enabled: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Install Docker
      yum:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Python pip
      yum:
        name: python-pip
        state: present

    - name: Install Docker Python module
      pip:
        name: docker

    - name: Pull Apache Docker image
      docker_image:
        name: httpd
        state: present

    - name: Run Apache container
      docker_container:
        name: apache_container
        image: httpd
        state: started
        ports:
          - "80:80"
        volumes:
          - /ansible/static_html:/usr/local/apache2/htdocs
