- name: Deploy Apache container using Docker
  hosts: localhost
  tasks:
    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install Docker Python module
      apt:
        name: python3-pip
        state: present

    - name: Install Docker module
      pip:
        name: docker

    - name: Pull Apache Docker image
      docker_image:
        name: httpd
        state: present

    - name: Run Apache container
      docker_container:
        name: apache_container
        image: httpd
        state: started
        ports:
          - "80:80"
        volumes:
          - /ansible/static_html:/usr/local/apache2/htdocs
